[project]
name = "park-attendance"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [ "beautifulsoup4", "boto3", "duckdb", "html5lib", "httpx", "lxml", "pandas", "pyarrow", "pyiceberg", "ratelimit", "requests", "tenacity",]
